name: Fathom
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipykernel
  - rioxarray
  - geopandas
  - ca-certificates
  - openssl
  - pytorch
  - torchvision
  - certifi
  - segmentation-models-pytorch
  - lightning
  - albumentations
  - matplotlib
  - ipywidgets
  - wget
  - black
  - nb_black
  - torchmetrics
  - scikit-image