# This is my configuration file for processing raw data.

# Please note: output_dir should not contain {resolution}_{size}
# as it will be added automatically by the processing script.

"tutorial_config":
  description: "Configuration used for the tutorial."

  # Data directory inside the root directory, this should be the one with the raw .tif images.
  # If null, will attempt root_dir / "data/raw/{resolution}_resolution".
  input_dir: "/share/gpu5/pmucha/fathom/levee-hunter/data/raw/tutorial_data"

  # If null, will assume it is root_dir / "data/raw/levees/levees.gpkg".
  levees_path: "/share/gpu5/pmucha/fathom/levee-hunter/data/raw/levees/levees.gpkg"

  # This should be the full path to the output directory. 
  # code will create {resolution}_{size} subdirectory in this directory, with images and masks subdirectories.
  output_dir: "/share/gpu5/pmucha/fathom/levee-hunter/data/intermediate/tutorial_data"

  # Resolution of the input data.
  # '1m' stands for 1 meter; another option might be '13' for 1/3 arc second.
  resolution: "1m"

  # Final size of the images after splitting, in pixels.
  # Note for segmentation models it often needs to be divisible by 32.
  final_size: 544

  # Overlap of the images after splitting. How much the smaller images will overlap with each other.
  overlap: 0

  # Percentage of empty images to keep. Eg, if there are 100 non-empty, if set to 0.2, there will be 20 empty.
  keep_empty: 0.2

  # Invert the images. If true, then 0 pixels will be target and 1 pixels will be background.
  invert: true

  # Mask configuration: Set mask_type to null if not used. Other options are currently: 'dilated', 'gaussian'.
  mask_type: null

  # Dilation size (10 is the default value). 
  # Does not matter if mask_type is null, but best to set to default value.
  dilation_size: 10

  # Gaussian sigma (5 is the default value).
  # Does not matter if mask_type is null, but best to set to default value.
  gaussian_sigma: 5

##########################################################################################
"13_636":
  description: "Configuration for processing 1/3 resolution raw data. Results in no pixels loss."

  input_dir: "/share/gpu5/ucapmgb/data/raw/13_resolution_original"

  levees_path: "/share/gpu5/pmucha/fathom/levee-hunter/data/raw/levees/levees.gpkg"

  output_dir: "/share/gpu5/ucapmgb/data/intermediate/"

  resolution: "13"

  # Final size of the images after splitting.
  # For 1/3 arc second resolution, 636 splits the 10812 pixel image perfectly.
  final_size: 636

  overlap: 0

  keep_empty: 0.2

  invert: true

  mask_type: null

  dilation_size: 10

  gaussian_sigma: 5

##########################################################################################

"1m_1024":
  description: "Configuration for processing 1m resolution raw data."

  input_dir: "/share/gpu5/pmucha/fathom/levee-hunter/data/raw/1m_resolution"

  levees_path: "/share/gpu5/pmucha/fathom/levee-hunter/data/raw/levees/levees.gpkg"

  output_dir: "/share/gpu5/pmucha/fathom/levee-hunter/data/intermediate/"

  resolution: "1m"

  # Final size of the images after splitting.
  # For 1/3 arc second resolution, 636 splits the 10812 pixel image perfectly.
  final_size: 1024

  overlap: 0

  keep_empty: 0.2

  invert: true

  mask_type: null

  dilation_size: 10

  gaussian_sigma: 5

  ##########################################################################################